import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import "@nomicfoundation/hardhat-verify";
import "@openzeppelin/hardhat-upgrades";
import "solidity-coverage";
import "hardhat-gas-reporter";
import dotenv from "dotenv";

dotenv.config();

function privateKey(): string {
  const pk = process.env.DEPLOYER_PRIVATE_KEY;
  if (!pk) throw new Error("DEPLOYER_PRIVATE_KEY not set in .env");
  return pk.startsWith("0x") ? pk : `0x${pk}`;
}

function rpcUrl(network: string): string {
  const key = `${network.toUpperCase().replace(/-/g, "_")}_RPC_URL`;
  const url = process.env[key];
  if (!url) throw new Error(`${key} not set in .env`);
  return url;
}

function apiKey(network: string): string | undefined {
  const key = `${network.toUpperCase()}_API_KEY`;
  return process.env[key];
}

const accounts = [privateKey()];

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.27",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
      viaIR: true,
    },
  },

  networks: {
    hardhat: {
      chainId: 31337,
      allowUnlimitedContractSize: true,
      mining: {
        auto: true,
        interval: 0,
      },
    },

    sepolia: {
      url: rpcUrl("sepolia"),
      accounts,
      chainId: 11155111,
    },

    bsc_testnet: {
      url: rpcUrl("bsc_testnet"),
      accounts,
      chainId: 97,
    },

    amoy: {
      url: rpcUrl("amoy"),
      accounts,
      chainId: 80002,
    },

    palm_testnet: {
      url: rpcUrl("palm_testnet"),
      accounts,
      chainId: 11297108099,
    },

    base_sepolia: {
      url: rpcUrl("base_sepolia"),
      accounts,
      chainId: 84532,
    },
  },

  etherscan: {
    apiKey: {
      sepolia: apiKey("ETHERSCAN") ?? "",
      bscTestnet: apiKey("BSCSCAN") ?? "",
      amoy: apiKey("POLYGONSCAN") ?? "",
      palmTestnet: apiKey("PALMSCAN") ?? "",
      baseSepolia: apiKey("BASESCAN") ?? "",
    },

    customChains: [
      {
        network: "palmTestnet",
        chainId: 11297108099,
        urls: {
          apiURL: "https://api-testnet.palm.io/api",
          browserURL: "https://testnet.palm.io",
        },
      },
      {
        network: "baseSepolia",
        chainId: 84532,
        urls: {
          apiURL: "https://api-sepolia.basescan.org/api",
          browserURL: "https://sepolia.basescan.org",
        },
      },
    ],
  },

  gasReporter: {
    enabled: process.env.REPORT_GAS === "true",
    currency: "USD",
    coinmarketcap: process.env.COINMARKETCAP_API_KEY,
    gasPriceApi: "https://api.etherscan.io/api?module=proxy&action=eth_gasPrice",
    token: "ETH",
    showMethodSig: true,
    onlyCalledMethods: false,
    include: ["contracts/**/*.sol"],
    exclude: [],
    outputFile: "gas-report.txt",
    noColors: true,
    L1Etherscan: "https://api.etherscan.io/api",
    L2Etherscan: "https://api-optimistic.etherscan.io/api",
    maxMethodDiff: 5,
    maxMethodCallers: 5,
    showTimeSpent: true,
    excludeAutoGeneratedGas: false,
    rst: false,
    rstTitle: "Gas Report",
    showUncalledMethods: true,
  },

  typechain: {
    outDir: "typechain-types",
    target: "ethers-v6",
    alwaysGenerateOverloads: true,
    discriminateTypes: true,
    tsNocheck: false,
    dontOverrideCompile: false,
  },

  mocha: {
    timeout: 120_000,
    bail: process.env.CI === "true",
  },
};

export default config;
